version: "3.9"

services:
  postgres:
    image: postgres:14.2-alpine3.15
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT-5432}:${POSTGRES_PORT-5432}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME-postgres}
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  mlflow:
    container_name: mlflow
    build:
      context: .
    ports:
      - ${MLFLOW_PORT-80}:${MLFLOW_PORT-80}
    depends_on:
      - postgres
    environment: 
      PORT: ${MLFLOW_PORT-80}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_ARTIFACT_URI: ${MLFLOW_ARTIFACT_URI-./mlruns}
      MLFLOW_DB_DATABASE: ${POSTGRES_DB_NAME-postgres}
      MLFLOW_DB_DIALECT: postgresql
      MLFLOW_DB_HOST: postgres
      MLFLOW_DB_PASSWORD: ${POSTGRES_PASSWORD-postgres}
      MLFLOW_DB_PORT: ${POSTGRES_PORT-5432}
      MLFLOW_DB_USERNAME: ${POSTGRES_USER-postgres}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD-mlflow}
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME-mlflow}
      MLFLOW_SQLALCHEMYSTORE_POOL_CLASS: NullPool

volumes:
  postgres-db-volume: